#!/bin/sh
host="admin@sso.eipystyilman.beer"
systemddir="/etc/systemd/system"
if [ "$1" != "host" ]; then
    zip -r hopperbot.zip Pipfile bot.py hopperbot.service  modules run.sh
    scp deploy hopperbot.zip ${host}:
    exec ssh $host sudo ./deploy host
fi
zipfile=$PWD/hopperbot.zip
unzip=`which unzip` # with this we don't need path
systemctl stop hopperbot.service
cd /home/hopperbot/HopperBot
su -s /bin/sh -c "${unzip} -o ${zipfile}" hopperbot
su -s /bin/sh -c "pipenv install" hopperbot
cp hopperbot.service ${systemddir}/
systemctl daemon-reload
systemctl start hopperbot.service
